platform :ios, '9.0'

target 'ta-lib-swift_Example' do
	
	use_frameworks!
	inhibit_all_warnings!
	
  	pod 'ta-lib-swift', :path => '../'

  	target 'ta-lib-swift_Tests' do
    	inherit! :search_paths

  end
end
